# Generated by Django 3.0.3 on 2020-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=256, unique=True)),
                ('worker', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=2048)),
            ],
        ),
    ]
